### ISSUE TITLE
Consider re-factoring how property definitions are stored and inherited

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-state#133]
This is my attempt to capture some of what @latentflip and I just discussed. 

In order to disambiguate the extra stuff that happens when you call `extend` on `state`.

It merges props, session, and derived. We talked about potentially having some way to access and edit that definition. This would let you choose what you're adding/removing/merging instead of oversimplifying it by calling `extend` when it really does more than that. It would potentially also help with the fact that ampersand doesn't work well with ES6 of coffeescript's class stuff. Lots of questions, still, but wanted to open this so we don't forget.

**Comment by latentflip** [comment]
So I had an initial play with this today. An initial observation:

### es6 classes don't let you set properties on the prototype, only methods.

i.e. this will never work as it's syntactically invalid.

```js
class Foo extends AmpersandState {
  props: {
    foo: 'string'
  }
}
```

so you either have to make it a getter, or a method

```js
class Foo extends AmpersandState
  get props() {
    return {
      foo: 'string'
    }
  }
  //or

  props() {
    return {
      foo: 'string'
    }
  }
}
```

I have a first pass of this that works with es6 classes, will push it to a branch for discussion.

**Comment by latentflip** [comment]
Alright, so here's a first attempt at supporting es6 https://github.com/AmpersandJS/ampersand-state/compare/es6-support-poc

## Basic premise

The changes to state are actually pretty minimal. The basic premise is that the extend method in state currently (i.e. when you do `var MyState = State.extend({ ... })` looks for `props`, `session`, `derived`, etc in the object you pass to extend, and creates a new constructor + prototype, defining properties etc on the prototype, and copying over any methods, and so on.

In es6 that won't happen, as the extend method never gets called, so we have to do it in the constructor instead. So when you do:

```js
class MyState extends AmpersandState {
  get props() {
    return {
      name: 'string'
    };
  }
}
```

The default constructor will check if it seems to have been created via an es6 like class, and if so, it will check for `props()` getter/function and add those properties to the instantiated object itself.

## Caveats

### Inheritance
The main issue is that the inheritance process has changed. The old extends approach will naturally merge in props from a "subclass" with props defined on the parent class", as the multiple extends will run in order.

```js
var MyClass = State.extend({
  props: {
    name: 'string',
    age: 'any' 
  }
}).extend({
  props: {
    age: 'number'
    height: 'number'
  }
})
```

So here, the resultant class (extended twice) will have `{ name: string, age: number, height: number }`, props being overwritten/added on each extend.

With es6 this won't work, as if you redefine props on a subclass it will just replace them (or more accurately will appear lower in the prototype chain and the parent ones won't be considered/accessed).

To deal with this, you can obviously grab from super and extend, I've added a method to do this, which currently just proxies to _.extend. I can foresee for views though, we may wish to have a more complex helper method. Ultimately, the above would be written something like this in es6, with the current implementation:

```js
class Base extends AmpersandState {
  get props() {
    return {
      name: 'string',
      age: 'any'
    };
  }
}

class BasePlusPlus extends Base {
  get props() {
    return this._mergeProps(super.props, {
      age: 'number',
      height: 'number'
    }
  }
}
```

### Getters vs functions

As described above, there's no way in es6 classes to define properties on the prototype within the class body, so, this will **not** work:

```js
class Foo extends State {
  props: {
    name: 'string'
  }
}
```

To deal with this, firstly I've made the extension method use `_.result`, allowing it to be a function instead. This isn't really that big of a drawback on es6 anyway, since if you were wanting to inherit down a chain of classes using `this._mergeProps` you'd have to make them a function anyway.

```js
class Foo extends State {
  props: function () {
    return {
      name: 'string'
    };
  }
}
```

For configuration options, i.e. `extraProperties: allow` we could just do the same. Though I haven't actually changed that behaviour, since I realised the way to make an almost-a-instance-property with es6 is to use a getter, e.g.:

```js
class Foo extends State {
  get extraProperties() { return 'allow' }
}
```

Maybe we should make all of those use result or something, I'm not sure.

### Performance

So, this is the big one, in a way. We've gone from creating a bunch of defined properties on the prototype at "class creation time" in `State.extend` to doing it on every instantiation of an object. This has both memory and performance implications. I added a benchmark showing that it's around 10 times slower to instantiate an object using the es6 classes vs `.extend`, and I don't think that's really es6, it's just a nature of the extra work being done in the constructor.

In many cases this probably won't matter because, a) it's still gonna be fairly fast, b) you probably aren't going to be instantiating a crap-ton of state objects all at once. But it still kinda sucks.

A possible mitigation is the `seal` method (this needs a better, less ambiguous name) I've added to AmpersandState (to the "class" not to the prototype). Seal basically performs the ahead-of-time-set-up-the-prototype work once for the class. It probably has some issues, like if you go on to then extend a sealed class weird things may happen (duplication of property definitions mostly, probably), but it's a start, and _almost completely eliminates perf issues_.

```js
class MyState extends AmpersandState {
  get props() {
    name: 'string'
  }
}

MyState.seal(); //woo free performance
```

## Status

This ain't perfect, but it also ain't half bad. Probably `_ampersandConstructed()` and `_sealed` and `seal()` need better names. We need to think about where/when to use _.result, and how to explain the differences between the two approaches to people. But, I think this could just about land pretty close to how this is right now.

I intentionally did not spend too long thinking about rethinking how definition etc etc all works internally as you mentioned in the original comment on this issue @HenrikJoreteg, as it seemed to make sense to see how it felt without trying to make significant changes.

## So.... thoughts?

**Comment by fritzy** [comment]
I doubt es6 is very optimized in the various engines yet. Is FF the same 10x ratio?

**Comment by aredridel** [comment]
ES6 isn't even _implemented_ in various engines yet.

**Comment by prust** [comment]
@latentflip:

> you probably aren't going to be instantiating a crap-ton of state objects all at once

I realize this isn't the primary use-case for Ampersand, but we work on a big desktop app (like node-webkit, but with a custom chromium build) that frequently instantiates hundreds of backbone model objects and occasionally instantiates a thousand at a time.

We had some performance problems a few months ago and when I measured, one of the problem areas was that we were creating getters/setters on every instance. Moving them to the prototype resulted in a measurable, across-the-board performance improvement for our app. It would be a shame to migrate to ampersand state objects and have a performance degradation...

**Comment by HenrikJoreteg** [comment]
I completely agree, we don't want to create a memory hog. I don't think doing it per-instance is a great idea and I think we should resolve the issues @prust is talking about as well.

**Comment by latentflip** [comment]
Some updated thoughts/responses:

* It's entirely possible we just plain don't want to support es6 classes, as the cons may outweigh the pros.  If we don't, I think we do need some way of flagging to devs that they're trying to do something that's not going to work though, as we're already seeing folk in gitter trying to use classes, and it sort-of-but-not-really-working.
* @fritzy the perf difference is due to the work being done in the constructor, rather than anything to do with es6 itself.
* @fritzy / @aredridel yes, es6 is still not implemented in a lot of places, but transpilation is only getting more popular, a la http://6to5.org/
* @prust / @HenrikJoreteg agreed, I don't want to ship a 10x performance decrease + memory hog either. Hence the potential for the `seal()` approach. To be clear, these changes wouldn't affect existing apps at all - only new apps trying to use es6 classes.

I guess the options really seem to be:

1) Say that we aren't going to support es6 classes in this way, and find some way of flagging to devs that they're doing it wrong when they try and use classes.
2) Support classes, and tell people to use the `seal()` call to speed things up, possibly with dev warnings when they forget to use seal (or whatever we'd call it).

In retrospect, I think at this stage I'd be pretty happy with either one. Possibly the simplest for now is 1) until we see increased es6 adoption and demand for a rethink/see what approach other frameworks take to all this?

**Comment by prust** [comment]
@latentflip,

> these changes wouldn't affect existing apps at all - only new apps trying to use es6 classes

Ah, thanks for clarifying, I hadn't understood that. So it wouldn't affect us unless/until we started using es6 classes, and in that transition, we could also transition to seal().

**Comment by latentflip** [comment]
@prust correct.

**Comment by latentflip** [comment]
Assuming we go with 2), that mostly closes the es6 (and coffeescript) side of this question, though there's possibly still some thought to be done around the original premise of @HenrikJoreteg's suggestions more generally.

**Comment by wcourtney** [comment]
Sorry to join this conversation so late but I just started playing with 6to5/Babel this week and was immediately interested to see how ES6 might be integrated into Ampersand. 

In your example case of constructor chaining above, I think that problem would be mitigated in ES6 using the class constructors as follows (mimicking your example classes above):
```js
class Base{
  constructor () {
    // Set default Base properties
    this.props = {
      name: 'string',
      age: 'any'
    };
  }
}

class BasePlusPlus extends Base{
  constructor () {
    // Build super object
    super(); 

    // Set BasePlusPlus props
    Object.assign(this.props, {
        age : 'number',
        height: 'number'
    });
  }
}
```

Invoking `new BasePlusPlus().props` would produce an object that looks like 
```
{ name: string, age: number, height: number }
``` 
...just as you'd expect in the existing style of chaining.

What do you think?

**Comment by pgilad** [comment]
If you can detect support for ES6, perhaps all getters/setters can be dropped and used with a proxy method. That way all `props` `states` and `derived` are naturally available with direct access through proxy, and don't need to be defined as a getter setter - thus you might see a huge performance benefit in large objects.

I'm not sure how slower the access to these properties will be.

**Comment by aredridel** [comment]
Lots slower.

**Comment by jokeyrhyme** [comment]
@latentflip am I characterising your approach correctly in that it takes the existing AmpersandState and does the minimum necessary to it to achieve the same outcomes for when the input in ES2015 `class` syntax?

@HenrikJoreteg maybe what is necessary here is a ground-up reimagining of AmpersandState as an ES2015/2016-native solution? What if something like [@decorators](https://github.com/wycats/javascript-decorators) were used instead of having `props` for validation? What if validation and event emitters were mixins that could be used without needing to inherit from AmpersandState?

**Comment by schmittyjd** [comment]
Any updates on this?

**Comment by ConneXNL** [comment]
+1 Still wanting typescript support :)

**Comment by latentflip** [comment]
The update on this is that for the time being, we won't be tweaking things such that es6 classes, a la, `class MyState extend AmpersandState { ... }` will work.

I've been doing a lot more es6 work recently, and while it would be nice if this could _just work_, I'm fairly sure that it cannot without significant workarounds, or by taking a fairly significant perforance hit.

There's an interesting parallel in the react community, where they are trying to make es6 components work, and they sort of do, but with a bunch of tradeoffs that mean you cannot always use es6 classes, or if you do you need to use a bunch of workarounds.

I don't want us to end up in the situation where we are trying to support both, but that people will need to fallback to the `.extend({})` alternative, because the es6 version can't support what they're trying to do; or that they're trying to do something in the es6 version that looks like it should work from an `extend` example, but doesn't.

As such, it'd seem that the benefits of even trying to make this work are, at present, pretty well outweighed by the drawbacks.

That's not to say that won't change as es7 features like decorators become popular, but those features are still in draft, let alone seeing wide community adoption. 

It may be that there's still some benefit to tweaking how we do the extend/and providing more hooks for changing the definition, as per @HenrikJoreteg's original point; but that's a separate discussion from trying to provide es6 class support which this has become.

**Comment by EvanCarroll** [comment]
Just out of curiosity, conceding to a lack of es6 experience. Without migrating to classes, is there a way to make the fat-arrow syntax work with Ampersand for methods on classes?

For instance, would it be possible to ever do..

```javascript
var Workspace = BaseRouter.extend({
    routes: {
        home: () => {
            this.navigate("/")
        }
    }
})
```

Airbnb's style guide requires fat-arrow syntax for methods, but that changes the value of `this` which in turn requires a different sort of class-syntax, one where the this lexical to the method refers to the object, and not just the inner-most object representing routes.

**Comment by jokeyrhyme** [comment]
@evancarroll

how about object method shorthand ? https://github.com/airbnb/javascript#3.5

```js
var Workspace = BaseRouter.extend({
    routes: {
        home () {
            this.navigate("/")
        }
    }
})
```

**Comment by EvanCarroll** [comment]
That would work in that context, but what about for something like this...

var View = BaseView.extend({
    'events': {
        'submit': (event) => {
            this.model.set('key', 'value');
        }
    }
});

It gets trickier, what people want is one idiom to cover all this stuff.
